all: selezionaMultipli1 selezionaMultipli2

selezionaMultipli1: selezionaMultipli1.c
	gcc -o selezionaMultipli1 -Wall -std=c11 selezionaMultipli1.c
selezionaMultipli2: selezionaMultipli2.c
	gcc -o selezionaMultipli2 -Wall -std=c11 selezionaMultipli2.c

