all: provaEsame2-a provaEsame2-b
provaEsame2-a: provaEsame2-a.c
	gcc -Wall -std=c11 -o provaEsame2-a provaEsame2-a.c
provaEsame2-b: provaEsame2-b.c
	gcc -Wall -std=c11 -o provaEsame2-b provaEsame2-b.c
